

services:
  pg1:
    build:
      context: ./postgres/pg1
    restart: unless-stopped
    container_name: pg1
    environment:
      - PGDATA=/var/lib/postgresql/data
      - PGENCODING=UTF8
      - PGLOCALE=en_US.UTF8
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./pg1/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pg-network


  pg2:
    build:
      context: ./postgres/pg2
    restart: unless-stopped
    container_name: pg2
    environment:
      - PGDATA=/var/lib/postgresql/data
      - PGENCODING=UTF8
      - PGLOCALE=en_US.UTF8
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./pg2/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - pg-network

  pgpool:
    build: ./pgpool
    restart: always
    container_name: pgpool
    command: pgpool -f /etc/pgpool2/pgpool.conf -F /etc/pgpool2/pcp.conf -n
    ports:
      - "5434:5432"
    volumes:
      - ./pgpool/conf:/etc/pgpool2
    networks:
      - pg-network

networks:
  pg-network:
    driver: bridge